---
#Variables del cliente NFS
nfs_server_ip: "10.0.32.253"
nfs_server_path: "/mnt/DiscosRapidos/PruebaRapidosX3"
nfs_mount_point: "/mnt/nasFAST"
nfs_mount_options: "ro,defaults,_netdev 0 0"

#para ver lo exportado por un servidor NFS
#showmount -e [ip]"