---

# Para ejecutar este playbook:
#    ansible-playbook -i ../../equiposSMRD.ini sencillo.ansible.yaml --ssh-extra-args="-o StrictHostKeyChecking=no"


# Simple playbook to return machine information (hostname, IP address, and MAC address)
- name: Gather system information
  hosts: all
  gather_facts: yes  # Need to gather facts to get system information
  tasks:
    - name: Display system information
      debug:
        msg: |
          Hostname: {{ ansible_hostname }}
          IP Address: {{ ansible_default_ipv4.address }}
          MAC Address: {{ ansible_default_ipv4.macaddress }}

